# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-05 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.FileField(upload_to='media/'),
        ),
    ]
